// <auto-generated />
namespace Inventory_Management_System_PC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User));
        
        string IMigrationMetadata.Id
        {
            get { return "202511160911515_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
