// <auto-generated />
namespace Inventory_Management_System_PC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SupplierSupplyStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupplierSupplyStock));
        
        string IMigrationMetadata.Id
        {
            get { return "202503241717000_SupplierSupplyStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
